### ISSUE TITLE
Four Legs when playing with Gmod Legs Addon

### ISSUE THREAD

**Issue by Losfrail** [VictorienXP/gmod-enhanced-camera-2#19]
[This is the Add-on By the Way.](https://steamcommunity.com/sharedfiles/filedetails/?id=112806637)

I do not know why this happens, all I know is that it might be due to a mod conflict. If it's not possible to fix, do not worry. But i'd be nice if both mods would be able to co-exist at the same time (so that Gmod Legs could have it's functionality of feet animations shared.)

Also, I went through the ardurous process of un-installing all addons except those two and this one:
https://steamcommunity.com/sharedfiles/filedetails/?id=2443976641
As well as this ones (which add materials):
https://steamcommunity.com/sharedfiles/filedetails/?id=730187817
https://steamcommunity.com/sharedfiles/filedetails/?id=730187817

[Bug most visible when crouching and using Two-Handed weapons.](https://imgur.com/a/4zf6AQy)

**Comment by VictorienXP** [comment]
I don't think this will/should be fixed because both Enhanced Camera 2 and Gmod Legs 3 have basically the same goal with a different vision.

So you have to choose one or the other.

If there are really things you prefer about Gmod Legs 3 that you want to see on Enhanced Camera 2, feel free to open a new issue about it.
